server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        expires 0;
        try_files $uri $uri/ /index.html;
    }
}
